services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: database
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/node/database.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: